<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-24T18:17:44 IST" name="Default suite" finished-at="2024-04-24T18:18:59 IST" duration-ms="75083">
    <groups>
    </groups>
    <test started-at="2024-04-24T18:17:44 IST" name="Default test" finished-at="2024-04-24T18:18:59 IST" duration-ms="75083">
      <class name="com.basic.second">
        <test-method is-config="true" signature="OpenWindow()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:17:44 IST" name="OpenWindow" finished-at="2024-04-24T18:17:54 IST" duration-ms="9949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenWindow -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:17:54 IST" name="loginTest" data-provider="loginData" finished-at="2024-04-24T18:18:04 IST" duration-ms="10629" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[smith@mailinator.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sdfsfdsfdor.com]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login was not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login was not successful
at org.testng.Assert.fail(Assert.java:99)
at com.basic.second.loginTest(second.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:04 IST" name="tearDown" finished-at="2024-04-24T18:18:05 IST" duration-ms="269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="OpenWindow()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:05 IST" name="OpenWindow" finished-at="2024-04-24T18:18:13 IST" duration-ms="8342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenWindow -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:13 IST" name="loginTest" data-provider="loginData" finished-at="2024-04-24T18:18:24 IST" duration-ms="10664" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[smithmailinator.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[smih@mailinator.com]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login was not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login was not successful
at org.testng.Assert.fail(Assert.java:99)
at com.basic.second.loginTest(second.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:24 IST" name="tearDown" finished-at="2024-04-24T18:18:24 IST" duration-ms="228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="OpenWindow()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:24 IST" name="OpenWindow" finished-at="2024-04-24T18:18:34 IST" duration-ms="10703" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenWindow -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:34 IST" name="loginTest" data-provider="loginData" finished-at="2024-04-24T18:18:45 IST" duration-ms="10632" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login was not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login was not successful
at org.testng.Assert.fail(Assert.java:99)
at com.basic.second.loginTest(second.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:45 IST" name="tearDown" finished-at="2024-04-24T18:18:45 IST" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="OpenWindow()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:45 IST" name="OpenWindow" finished-at="2024-04-24T18:18:48 IST" duration-ms="2608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenWindow -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:48 IST" name="loginTest" data-provider="loginData" finished-at="2024-04-24T18:18:59 IST" duration-ms="10538" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[smith@mailinator.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[smith@mailinator.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.basic.second@243c4f91]" started-at="2024-04-24T18:18:59 IST" name="tearDown" finished-at="2024-04-24T18:18:59 IST" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.basic.second -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
